
CREATE TABLE MEAL (
 TIME_MEAL_ORDERED TIMESTAMP DEFAULT NOW()
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT
);

CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
);


INSERT INTO INGREDIENT (NAME,PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
VALUES ('Eggs',0.50, false, true, false, true);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
VALUES ('Bread', 1.00, false, true, true, false);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
VALUES ('Beef Patty',1.50, false, false, false, true);

INSERT INTO INGREDIENT (NAME,PRICE,CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
VALUES ('Lettuce',0.20, false, true, true, true);

INSERT INTO INGREDIENT (NAME,PRICE,CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE)
VALUES ('Yoghurt',1.00, true, true, false, true);






#1
ALTER TABLE INGREDIENT
ADD CONSTRAINT UNIQUE(NAME)

#2
ALTER TABLE INGREDIENT
MODIFY NAME VARCHAR(255) not null;

#3
ALTER TABLE INGREDIENT
MODIFY PRICE DOUBLE not null;

#4
ALTER TABLE INGREDIENT
MODIFY CONTAINS_LACTOSE BOOLEAN not null;

#5
ALTER TABLE INGREDIENT
MODIFY VEGETARIAN BOOLEAN not null;

#6
ALTER TABLE INGREDIENT
MODIFY VEGAN BOOLEAN not null;

#7
ALTER TABLE INGREDIENT
ADD CONSTRAINT UNIQUE(NAME)
MODIFY GLUTEN_FREE not null

