CREATE TABLE MEALS (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT,
  ORDERED_MEALS TIMESTAMP
);

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Spaghetti Bolognese', 12.99, 600, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Grilled Chicken Sandwich', 8.99, 400, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Pesto Pasta', 10.99, 550, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Steak and Mash', 19.99, 800, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Sushi Platter', 15.99, 700, NOW());

CREATE TABLE MEALS_TABLE AS
SELECT * FROM MEALS;

/* QUERY*/

SELECT COUNT(*) AS NUMBER_OF_MEALS FROM MEALS_TABLE
GROUP BY NAME;


SELECT SUM(PRICE) AS TOTAL_REVENUE FROM MEALS_TABLE
WHERE PRICE > 15;

SELECT COUNT(CALORIES) AS HIGH_CALORIES_MEALS FROM MEALS_TABLE
WHERE CALORIES > 500
GROUP BY NAME;


SELECT SUM(PRICE) AS PARTICULAR_SUM FROM MEALS_TABLE
WHERE LOWER(NAME) LIKE '%s%';


SELECT COUNT(ORDERED_MEALS) AS ORDERS FROM MEALS_TABLE
WHERE ORDERED_MEALS < '2023-06-20 10:18:00'
GROUP BY ORDERED_MEALS;