

CREATE TABLE MEALS (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT,
  ORDERED_MEALS TIMESTAMP
);

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Spaghetti Bolognese', 12.99, 600, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Grilled Chicken Sandwich', 8.99, 400, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Pesto Pasta', 10.99, 550, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Steak and Mash', 19.99, 800, NOW());

INSERT INTO MEALS(NAME, PRICE, CALORIES, ORDERED_MEALS)
VALUES('Sushi Platter', 15.99, 700, NOW());


CREATE TABLE MEALS_TABLE AS
SELECT * FROM MEALS;

/* QUERY */
SELECT MEAL_NAME, MAX(PRICE) FROM MEAL_ORDER
WHERE CALORIES > 500
GROUP BY MEAL_NAME;


SELECT MEAL_NAME, AVG(CALORIES) FROM MEAL_ORDER
WHERE PRICE > 15
GROUP BY MEAL_NAME;


SELECT MEAL_NAME, PRICE FROM MEAL_ORDER
HAVING PRICE = (SELECT MAX(PRICE) FROM MEAL_ORDER);


SELECT MEAL_NAME, AVG(PRICE) FROM MEAL_ORDER
GROUP BY MEAL_NAME, PRICE
HAVING PRICE < (SELECT AVG(PRICE) FROM MEAL_ORDER);


SELECT MEAL_NAME, PRICE, CALORIES FROM MEAL_ORDER
WHERE PRICE < (SELECT AVG(PRICE) FROM MEAL_ORDER) AND CALORIES > 600;